<?php

return [
    'Taux' => [
        1 => 945/1000,
        2 => 50/1000,
        3 => 5/1000
    ],
    'Rareté' => [
        1 => 'Commune',
        2 => 'Rare',
        3 => 'Ultra Rare'
    ],
    'Liste packs' => [
        'Pack 1' => 1,
        'Pack 2' => 2
    ],
    'Pack 1' => [
        'Nombre de cartes' => 69,
        'Prix' => 100,
        // Liste des id de cartes par rareté
        'Cartes' => [
            // Ne pas mettre d'accent sur la première lettre de chaques cartes sous peine d'éroner le tri du datatable
            'Noms' => [
                1 => 'Guerrier Humain',
                2 => 'Lancier Humain',
                3 => 'Guerrier Elfe',
                4 => 'Guerrier Nain',
                5 => 'Haut Elfe',
                6 => 'Guerrier Squelette',
                7 => 'Guerrier Gobelin',
                8 => 'Guerrier Orque',
                9 => 'Guerrier Zombie',
                10 => 'Roi Gobelin',
                11 => 'Archer Humain',
                12 => 'Arbalétrier Humain',
                13 => 'Archer Elfe',
                14 => 'Archer Nain',
                15 => 'Elfe Noir',
                16 => 'Archer Squelette',
                17 => 'Archer Gobelin',
                18 => 'Archer Orque',
                19 => 'Arbalétrier Orque',
                20 => 'Roi Squelette',
                21 => 'Archer Zombie',
                22 => 'Cavalier Humain',
                23 => 'Cavalier Elfe',
                24 => 'Cavalier Nain',
                25 => 'Orque Noir',
                26 => 'Cavalier Squelette',
                27 => 'Chevaucheur Gobelin',
                28 => 'Chevalier Humain',
                29 => 'Chevaucheur Orque',
                30 => 'Roi Sorcier',
                31 => 'Cavalier Zombie',
                32 => 'Goule',
                33 => 'Magicien',
                34 => 'Troll',
                35 => 'Berserker Orque',
                36 => 'Ensorceleur',
                37 => 'Elémentaliste',
                38 => 'Druide',
                39 => 'Loup Garou',
                40 => 'Loup-Garou Alpha',
                41 => 'Clerc',
                42 => 'Assassin',
                43 => 'Horde de Barbares',
                44 => 'Alchimiste',
                45 => 'Loup-Garou Chamane',
                46 => 'Enchanteur',
                47 => 'Zombie Gobelin',
                48 => 'Vampire',
                49 => 'Chariot Nain',
                50 => 'Capitaine Humain',
                51 => 'Rat Géant',
                52 => 'Roi Rat',
                53 => 'Meute de Loups-Garous',
                54 => 'Spectre',
                55 => 'Faucheur',
                56 => 'Démon',
                57 => 'Troll des Cavernes',
                58 => 'Troll des Montagnes',
                59 => 'Commandant Humain',
                60 => 'Roi Nain',
                61 => 'Chef Troll',
                62 => 'Seigneur Vampire',
                63 => 'Gobelin Chamane',
                64 => 'Orque Chamane',
                65 => 'Troll Chamane',
                66 => 'Lyche',
                67 => 'Wyvern',
                68 => 'Titan',
                69 => 'Dragon ancestral'
            ],
            'Rareté' => [
                1 => [
                    1,2,3,4,6,7,8,9,11,12,13,14,16,17,18,19,21,22,23,24,26,27,28,29,31,32,33,34,36,37,38,39,41,42,43,44,46,47,
                    48,49,51
                ],
                2 => [
                    5,15,25,35,45,50,52,53,54,55,56,57,58,63,64,65
                ],
                3 => [
                    10,20,30,40,59,60,61,62,66,67,68,69
                ],
            ]
        ],
    ],
    'Pack 2' => [
        'Quantité' => 39,
        'Prix' => 100,
        'Cartes' => [
            'Noms' => [
                1 => 'Archer',
                2 => 'Archère furtive',
                3 => 'Ballon',
                4 => 'Barbare',
                5 => 'Barbare enragé',
                6 => 'Bébé dragon',
                7 => 'Beta gargouille',
                8 => 'Bombardier',
                9 => 'Bouliste',
                10 => 'Championne Royale',
                11 => 'Chauve-souris',
                12 => 'Chevaucheur de cochon',
                13 => 'Chevaucheur du ciel',
                14 => 'Dragon',
                15 => 'Electro-dragon',
                16 => 'Gargouille',
                17 => 'Géant',
                18 => 'Géant Boxeur',
                19 => 'Gobelin',
                20 => 'Golem',
                21 => 'Golem de glace',
                22 => 'Golémites',
                23 => 'Grand gardien',
                24 => 'Guérisseuse',
                25 => 'Machine de combat',
                26 => 'Mineur',
                27 => 'Molosse de lave',
                28 => 'P.E.K.K.A',
                29 => 'Reine des archers',
                30 => 'Roi des barbares',
                31 => 'Sapeur',
                32 => 'Sorcier',
                33 => 'Sorcier de glace',
                34 => 'Sorcière',
                35 => 'Sorcière de la nuit',
                36 => 'Squelette',
                37 => 'Super P.E.K.K.A',
                38 => 'Valkyrie',
                39 => 'Yéti'
            ],
            'Rareté' => [
                1 => [
                    1, 3, 4, 6, 8, 9, 11, 12, 16, 19, 22, 25, 26, 31, 32, 34, 36, 38
                ],
                2 => [
                    2, 5, 7, 10, 13, 14, 17, 18, 20, 24, 27, 28, 33, 35
                ],
                3 => [
                    15, 21, 23, 29, 30, 37, 39
                ],
            ],
            'Images' => [
                1 => 'archer.png',
                2 => 'archere_furtive.png',
                3 => 'ballon.png',
                4 => 'barbare.png',
                5 => 'barbare_enrage.png',
                6 => 'bebe_dragon.png',
                7 => 'beta_gargouille.png',
                8 => 'bombardier.png',
                9 => 'bouliste.png',
                10 => 'championne_royale.png',
                11 => 'chauve_souris.png',
                12 => 'chevaucheur_de_cochon.png',
                13 => 'chevaucheur_du_ciel.png',
                14 => 'dragon.png',
                15 => 'electro_dragon.png',
                16 => 'gargouille.png',
                17 => 'geant.png',
                18 => 'geant_boxeur.png',
                19 => 'gobelin.png',
                20 => 'golem.png',
                21 => 'golem_de_glace.png',
                22 => 'golemites.png',
                23 => 'grand_gardien.png',
                24 => 'guerisseuse.png',
                25 => 'machine_de_combat.png',
                26 => 'mineur.png',
                27 => 'molosse_de_lave.png',
                28 => 'pekka.png',
                29 => 'reine_des_archers.png',
                30 => 'roi_des_barbares.png',
                31 => 'sapeur.png',
                32 => 'sorcier.png',
                33 => 'sorcier_de_glace.png',
                34 => 'sorciere.png',
                35 => 'sorciere_de_la_nuit.png',
                36 => 'squelette.png',
                37 => 'super_pekka.png',
                38 => 'valkyrie.png',
                39 => 'yeti.png'
            ]
        ]
    ]
];